### ISSUE TITLE
Wrong code generated by "Convert if-else into conditional expression" using p42 VSCode plugin v1.163.1 

### ISSUE THREAD

**Issue by doberkofler** [p42ai/js-assistant#57] opened 2022-11-07 10:59 UTC
I just noticed in my code that the following code snipped:

```typescript
function test(para: string, options?: string): string {
	let url = `url?para=${para}`;

	if (typeof options === 'string' && options.length > 0) {
		url += `&${options}`;
	}

	return url;
}
```

will be wrongly converted by p42 to:

```typescript
function test(para: string, options?: string): string {
	return typeof options === 'string' && options.length > 0 ? `&${options}` : `url?para=${para}`;
}
```

**Comment by lgrammel** [comment] 2022-11-07 11:22
Hi @doberkofler - thanks for the bug report! This issue was fixed in `v1.163.3`. Please try that version and re-open if it still occurs. 

Duplicate of #56

**Closed by lgrammel** 2022-11-07 11:22 UTC
